SERIE_KEYWORDS:
  CT:
    PRIMARY: ["knochen"]
    SECONDARY: ["weichteil"]
    EXCLUSION: []
  PT:
    PRIMARY: ["pet gk ctac", "qc fx", "wb_ctac", "wb ctac"]
    SECONDARY: []
    EXCLUSION: ["nac motion free", "pet exam report", "mip"]
  MR:
    EXCLUSION: ["carebolus", "localizer", "survey", "ds", "dixon", "haste", "t2-space-coronar"]
    PRIMARY: ["t1 tse", "t2 tse", "t2w_mvxd_sag", "t2w_tse_sag", "dyn", "dce mi fov", "dwi", "1400", "adc", "tracew"]
    SECONDARY: []
